object Versions {
    const val gradle = "4.1.3"
    const val kotlin = "1.4.32"
    const val safeArgsPlugin = "2.3.5"
    const val hiltPlugin = "2.31.2-alpha"
    const val core = "1.3.2"
    const val appCompat = "1.2.0"
    const val material = "1.3.0"
    const val constraintLayout = "2.0.4"
    const val navigation = "2.3.5"
    const val room = "2.3.0"
    const val coroutines = "1.4.3"
    const val lifecycle = "2.3.1"
    const val junit = "4.13.2"
    const val hilt = "2.28-alpha"
    const val hiltViewModel = "1.0.0-alpha01"
    const val timber = "4.7.1"
}